### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by msimonc** [Jishun/react-validated-input#1]
This looks Awesome! hope I can get it to work with my ES6 Webpack build project 

The install went fine: npm install react-validated-input --save

But in my .jsx when I:
import Input from 'react-validated-input'

I get console.log:  (it's there in node_modules?!) not seen this before.  Thx!

Module not found: Error: Cannot resolve module 'react-validated-input' in /Projects/TrailerShare/ts-client/app/components
resolve module react-validated-input in /Projects/TrailerShare/ts-client/app/components
  looking for modules in /Projects/TrailerShare/ts-client/node_modules
    resolve 'file' react-validated-input in /Projects/TrailerShare/ts-client/node_modules
      resolve file
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input is not a file
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input.js doesn't exist
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx doesn't exist
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6 doesn't exist
    resolve 'file' or 'directory' /Projects/TrailerShare/ts-client/node_modules/react-validated-input
      resolve file
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input is not a file
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input.js doesn't exist
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx doesn't exist
        /Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6 doesn't exist
      resolve directory
        directory default file index
          resolve file index in /Projects/TrailerShare/ts-client/node_modules/react-validated-input
            /Projects/TrailerShare/ts-client/node_modules/react-validated-input/index doesn't exist
            /Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.js doesn't exist
            /Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.jsx doesn't exist
            /Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.es6 doesn't exist
        use dist/react-validated-input.js from package.json
          resolve 'file' or 'directory' dist/react-validated-input.js in /Projects/TrailerShare/ts-client/node_modules/react-validated-input
            resolve file
              /Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js doesn't exist
              /Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.js doesn't exist
              /Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.jsx doesn't exist
              /Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.es6 doesn't exist
            resolve directory
              /Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js doesn't exist (directory default file)
              /Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js/package.json doesn't exist (directory description file)
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.es6]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.es6]
 @ ./app/components/address.jsx 28:27-59

**Comment by Jishun** [comment]
Hey Mark


Thanks for asking about it, i'll have to give it a try right now

I'll get back to you asap.
On Wed, Jul 13, 2016 at 10:34 AM, Mark Simon <notifications@github.com<mailto:notifications@github.com>> wrote:


This looks Awesome! hope I can get it to work with my ES6 Webpack build project

The install went fine: npm install react-validated-input --save

But in my .jsx when I:
import Input from 'react-validated-input'

I get console.log: (it's there in node_modules?!) not seen this before. Thx!

Module not found: Error: Cannot resolve module 'react-validated-input' in /Projects/TrailerShare/ts-client/app/components
resolve module react-validated-input in /Projects/TrailerShare/ts-client/app/components
looking for modules in /Projects/TrailerShare/ts-client/node_modules
resolve 'file' react-validated-input in /Projects/TrailerShare/ts-client/node_modules
resolve file
/Projects/TrailerShare/ts-client/node_modules/react-validated-input is not a file
/Projects/TrailerShare/ts-client/node_modules/react-validated-input.js doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6 doesn't exist
resolve 'file' or 'directory' /Projects/TrailerShare/ts-client/node_modules/react-validated-input
resolve file
/Projects/TrailerShare/ts-client/node_modules/react-validated-input is not a file
/Projects/TrailerShare/ts-client/node_modules/react-validated-input.js doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6 doesn't exist
resolve directory
directory default file index
resolve file index in /Projects/TrailerShare/ts-client/node_modules/react-validated-input
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.js doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.jsx doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.es6 doesn't exist
use dist/react-validated-input.js from package.json
resolve 'file' or 'directory' dist/react-validated-input.js in /Projects/TrailerShare/ts-client/node_modules/react-validated-input
resolve file
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.js doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.jsx doesn't exist
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.es6 doesn't exist
resolve directory
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js doesn't exist (directory default file)
/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js/package.json doesn't exist (directory description file)
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input.es6]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/index.es6]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.js]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.jsx]
[/Projects/TrailerShare/ts-client/node_modules/react-validated-input/dist/react-validated-input.js.es6]
@ ./app/components/address.jsx 28:27-59

**Comment by msimonc** [comment]
My project is pretty up to date re: build tools.
Any further info you need, feel free to let me know.  Thx!

**Comment by Jishun** [comment]
Thank you so much for reporting this to me @msimonc 
please upgrade to new version 0.0.9 which renamed the main entry js to index.js so that fits with webpack

**Comment by msimonc** [comment]
That's loading now, thanks!  Nothing happened when I did npm update or install.  I had to remove it from package.json first.  The spec is: "0.0.9" but all the others are: "^0.0.x" ?!  Thx again,
