### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by msimonc** [Jishun/react-validated-input#2]
Hi Jishun,
When is doValidate called in the Usage example?  Also, what does  validate={this.state.validation} do?  Perhaps some sample data?  Ideally usage examples for textarea, password, email, select, radio, checkbox would be great.  Thanks mate

**Comment by Jishun** [comment]
usage example now available at a test js file  
https://github.com/Jishun/react-validated-input/blob/master/project/test/entry.js
also published demo page at 
http://jishun.github.io/react-validated-input/

Thank you so much Mark!

**Comment by msimonc** [comment]
sweet
